.PHONY: all clean

all:
	@$(MAKE) all -C CreamView
	@$(MAKE) all -C curl
	@$(MAKE) all -C gopher
	@$(MAKE) all -C modules/about
	@$(MAKE) all -C modules/ftp
	@$(MAKE) all -C modules/www

clean:
	@$(MAKE) clean -C CreamView
	@$(MAKE) clean -C curl
	@$(MAKE) clean -C gopher
	@$(MAKE) clean -C modules/about
	@$(MAKE) clean -C modules/ftp
	@$(MAKE) clean -C modules/www
