TOP=..
include ${TOP}/Makefile.config

SUBDIR= libs core

all: all-subdir

install: install-subdir

deinstall: deinstall-subdir

clean: clean-subdir

cleandir: cleandir-subdir

proj-clean: proj-clean-subdir

depend: depend-subdir

include ${TOP}/mk/build.subdir.mk
